/**
types.ts
 * CAREERFORGE TYPE DEFINITIONS (v2026.03.03)
 * Documentation:
 * These interfaces define the data contract between the CLI, Gemini API,
 * and the automated browser application logic.
 */

export interface UserProfile {
  /** The full markdown content of the user's master profile */
  content: string;
}

export interface JobDetails {
  /** Job title as identified or provided by the user */
  title: string;
  /** Company name for tailoring and file naming */
  company: string;
  /** The raw job description text used for LLM context */
  description: string;
  /** * Optional: The source URL of the job posting.
   * Highly recommended for the automated 'apply' workflow.
   */
  jobUrl?: string;
}

export interface GeneratedAssets {
  /** The complete, stand-alone HTML string generated by Gemini 3 */
  resumeHtml: string;
}